---
title: THS2-GRP_sting
author: Himawork
date: '2020-05-27'
slug: THS2-GRP_2020-05-27_sting
categories:
  - HTML
tags:
  - Reports
  - Trade
  - sting
---

```{r Load_Functions, echo=FALSE, warning=FALSE}
# load packages and functions ----
suppressMessages({library(rvest); library(recharts)})
# range band cross rate test, generate 'bandTest' for SpyKplot()
bandCrotest <- function(Scode,Type = 'sting', range = c(50, 60), bandFrom = 30, bandNum = 4, status = F) {
  datK.old = readRDS('e:/tess/SpySto.RDS')[[Type]][[Scode]][['dailyK']]; bandRange = bandNum -1; bandRes = NULL
  if (length(datK.old$Date) < bandFrom) {
    print('bandFrom out of datK boundary, use default length of datK.')
    bandFrom = length(datK.old$Date)
  }
  # 
  for (b in bandFrom:(bandNum+1)) {
    bandMin = max(datK.old$HIGH[b:(b-bandRange)]) * range[1]/100 + min(datK.old$LOW[b:(b-bandRange)]) * (1 - range[1]/100)
    bandMax = max(datK.old$HIGH[b:(b-bandRange)]) * range[2]/100 + min(datK.old$LOW[b:(b-bandRange)]) * (1 - range[2]/100)
    NumCro<- length(grep('TRUE',(datK.old$LOW[b:(b-bandRange)] < bandMin & datK.old$HIGH[b:(b-bandRange)] > bandMax)))
    bandDate = datK.old$Date[b-bandRange];
    if (NumCro >= ceiling(bandNum * 0.6)) {
      bandTest = TRUE
      # cat(paste0(bandDate,'| bandMin: ',bandMin,'; bandMax: ',bandMax,'; NumCro: ',NumCro,'\n'))
      # cat(paste0(c(datK.old$LOW[b:(b-bandRange)] < bandMin & datK.old$HIGH[b:(b-bandRange)] > bandMax)));cat('\n')
      Hvalue = datK.old$HIGH[which(datK.old[,'Date'] == bandDate)]
      if (length(Hvalue) !=1) {Hvalue=bandMax}
      banddat = data.frame(Date = bandDate, Test = bandTest, NumCro = NumCro, High = Hvalue * 1.01)
      bandRes = rbind.data.frame(bandRes, banddat)
    } # else {cat(paste0(bandDate,'|\n'))}
  }
  # reture dataRes or status
  if (status) {
    if (!is.null(bandRes)) {
      return(ifelse((bandRes$Date[1] + 7) >= Sys.Date(),TRUE,FALSE))
    } else {return(FALSE)}
  } else {return(bandRes)}
}
# plot K-kines
SpyKplot = function(Scode = '', type = c('sting'), bandTestres = bandTest, viewNum = 30) {
  BuyScodeNum = names(readRDS('e:/tess/SpySto.RDS')[[type]])
  if (Scode %in% BuyScodeNum) {
    dataK = readRDS('e:/tess/SpySto.RDS')[[type]][[Scode]][['dailyK']]
    dataK = na.omit(dataK[duplicated(dataK$Date)==F,])
    if (nrow(dataK) < viewNum) {
      viewNum <- nrow(dataK)
      cat(paste0('ViewNum out of boundary. Use default ',nrow(dataK), ' nrows of dataK.\n'))    }
    # re-order date
    dataK = dataK[1:viewNum,]
    dataK = dataK[order(dataK$Date, decreasing = F),]
    # K line
    Kplot <-  echartr(dataK, as.character(Date), c('OPEN', 'CLOSE', 'LOW', 'HIGH'), type='k') %>%  
      # set_grid(width = 800, height = 300,widget = 'pane') %>%
      setXAxis(name='', axisLabel=list(rotate=45,textStyle=list(fontSize = 8.5))) %>%
      set_theme(width = 960,height = 300) %>%  set_legend(show = F)%>% 
      setYAxis(name="Price") %>% setToolbox(show = F,controls = c("dataZoom", "restore"), pos = 9)%>% 
      setTitle(subtitle =  paste0('dailyK_plot of ', Scode), pos =12,
               sublink = paste0("http://stockpage.10jqka.com.cn/", Scode)) %>%
      setTooltip(show=T, bgColor = "rgba(0,0,0,0)", textStyle = list(fontSize=8.5, color = 'black')) %>% 
      setDataZoom(fill=rgba(c(col2rgb('lightgreen'), 0.2)), handle=rgba(c(col2rgb('darkgreen'), 0.5)), range = c(50,100))
    if (length(bandTestres) < 1) {
      return(Kplot)
    } else {
      names(bandTestres) = c('xAxis','value','name','yAxis')
      Kplot.1 <- Kplot %>% addMP(data = bandTestres,symbol = 'pin',symbolSize =3,effect = list(show = F,color='green'))
      return(Kplot.1)
    }
  } else print(paste0(Scode,' is not in subdata of ',type))
}
# plot stock trading details
StoQplot = function(Scode = '', type = c('sting'), plot = c('StoIO', 'StoVP'), viewNum = 30) {
  BuyScodeNum = names(readRDS('e:/tess/SpySto.RDS')[[type]])
  if (Scode %in% BuyScodeNum) {
    Qplot.dat = readRDS('e:/tess/SpySto.RDS')[['sting']][[Scode]][['CStoDetail']]
    if (nrow(Qplot.dat) < viewNum) {
      viewNum <- nrow(Qplot.dat)
      cat(paste0('ViewNum out of boundary. Use default ',nrow(Qplot.dat), ' nrows of Qplot data.\n'))    }
    # re-order date 
    Qplot.dat = Qplot.dat[1:viewNum,]
    Qplot.dat = Qplot.dat[order(Qplot.dat$compTime, decreasing = F),]
    if (plot == "StoIO") {
      # stock in and out
      Qplot.dat = na.omit(Qplot.dat[duplicated(Qplot.dat$compTime)==F,c(1,10:15)])
      dat.melt = data.table::melt(Qplot.dat,id ='compTime',measure=c('StoIN.max','StoIN.mid','StoIN.min'))
      dat.melt2 = data.table::melt(Qplot.dat,id ='compTime',measure=c('StoOUT.max','StoOUT.mid','StoOUT.min'))
      dat.melt2$value = -dat.melt2$value # ; dat.melt$class = 'StoIN'; dat.melt2$class = 'StoOUT'
      Qplot = echartr(rbind.data.frame(dat.melt, dat.melt2), as.character(compTime), value, variable, 
                      type='area', subtype = 'stack') %>%
        setTitle(subtitle = "Trading quantity: StoOUT vs. StoIN", pos = 12, 
                 sublink = paste0("http://stockpage.10jqka.com.cn/", Scode)) %>%  
        setXAxis(name = "", axisLabel = list(rotate = 30, textStyle=list(fontSize = 8.5))) %>% setYAxis(name = "万元") %>%  
        setTooltip(show=T, trigger = 'axis', bgColor = "rgba(0,0,0,0)", textStyle = list(fontSize=9, color = 'black'), 
                   formatter= '{b}<br/> {a}: {c} <br/> {a1}: {c1} <br/> {a2}: {c2} 
                           <br/> {a3}: {c3} <br/> {a4}: {c4} <br/> {a5}: {c5} ') %>%
        set_theme(width = 960,height = 480, theme = 'macarons') %>% 
        setToolbox(show = T,controls = c("dataZoom", 'restore'), pos = 1) %>% 
        setDataZoom(fill=rgba(c(col2rgb('lightgreen'), 0.2)), handle=rgba(c(col2rgb('darkgreen'), 0.5)), range = c(50,100))
    } else if (plot == "StoVP") {
      # gauge plot of stock trading change
      Qplot.dat = na.omit(Qplot.dat[duplicated(Qplot.dat$compTime)==F,c(1,8,9)])
      BD.dat = rbind.data.frame(data.frame(value = Qplot.dat[,2], class = 'Vib/%'),
                                data.frame(value = Qplot.dat[,3], class = 'Tra/%'))
      BD.dat$date = Qplot.dat$compTime; BD.dat$value = round(BD.dat$value, 2)
      Qplot = echartr(BD.dat, as.character(date),value, class, type='area', subtype = 'stack') %>% 
        setTitle(subtitle = "Vibration(%) & Trading(%)", pos = 12,
                 sublink = paste0("http://stockpage.10jqka.com.cn/", Scode))  %>%  
        setXAxis(name = "", axisLabel = list(rotate = 30, textStyle=list(fontSize = 9))) %>% setYAxis(name = "(%)") %>%  
        setTooltip(show=T, trigger = 'axis', bgColor = "rgba(0,0,0,0)", textStyle = list(fontSize = 10, color = 'black'),
                   formatter= '{b}<br/> {a}: {c} <br/> {a1}: {c1} ') %>%
        set_theme(width = 960,height = 300, theme = 'macarons') %>% 
        setToolbox(show = T,controls = c("dataZoom", 'restore'), pos = 1) %>% 
        setDataZoom(fill=rgba(c(col2rgb('lightgreen'), 0.2)), handle=rgba(c(col2rgb('darkgreen'), 0.5)), range = c(50,100))
    }
    return(Qplot)
  } else print(paste0(Scode,' is not in subdata of ',type))
}
# trade report plot
tradePlot <- function(Scode) {
  tradeRe = readRDS('e:/tess/tradeRe.RDS')
  if (Scode %in% names(tradeRe)) {
    Sto.dat = tradeRe[[Scode]]
    Sto.dat[,c('buyN','sellN','holdN')] = Sto.dat[,c('buyN','sellN','holdN')] / (-100)
    Sto.dat = data.table::melt(Sto.dat,id ='date')
    Sto.dat = Sto.dat[order(Sto.dat$date, decreasing = F),]
    plot = echartr(Sto.dat, as.character(date), value, variable, type='area', subtype = 'stack') %>%
      setTitle(subtitle = paste0("Trading Reports of ", Scode), pos = 12, 
               sublink = paste0("http://stockpage.10jqka.com.cn/", Scode)) %>%  
      setXAxis(name = "", axisLabel = list(rotate = 30, textStyle=list(fontSize = 9))) %>% 
      setTooltip(show=T, trigger = 'axis', bgColor = "rgba(0,0,0,0)", textStyle = list(fontSize=9, color = 'black')) %>%
      setDataZoom(fill=rgba(c(col2rgb('lightgreen'), 0.2)), handle=rgba(c(col2rgb('darkgreen'), 0.5))) %>% 
      set_theme(width = 960,height = 480, theme = 'macarons') %>% 
      setToolbox(show = T,controls = c("dataZoom", 'restore'), pos = 1) %>% 
      set_legend(selected = c('buyN','sellN','holdN','price','cost'))
    return(plot)
  } else {cat(paste0('\nNo trade history of ', Scode,'\n'))}
}
# calculate profit
bandProfit <- function(Scode, bandRes = '', MaxHoldDays = 30, plot = F, mn = 10, baseHold = 0, 
                       Maxband = 1, viewNum = 30, Proless = 200) {
  datK.old = na.omit(readRDS('e:/tess/SpySto.RDS')[['sting']][[Scode]][['dailyK']])
  if (length(bandRes) < 1) {
    print(paste0('No profit band of stock ',Scode))
    if (plot) {
      SpyKplot(Scode,type = 'sting',bandTestres = bandRes,viewNum = viewNum)}
  } else {
    bandRes$Date = as.character(bandRes$Date); profit = 0; MaxTestDays = Maxband * 5; 
    Buydat = NULL; BS.dat = NULL; BS.datT = NULL
    for (d in bandRes$Date) {
      FinalHold = 0; HoldStoNum = 0; money = 50000; 
      for (m in 1:MaxTestDays) {
        Sday = which(datK.old$Date==d) - m
        Sday <- ifelse(length(Sday) ==1,Sday,0)
        ## test buy env and buying new stocks
        if (Sday > 1) {
          Sdat = datK.old[c(Sday),]; Sdat$Date = as.character(Sdat$Date) 
          # Sdat = datK.old[c(Sday,Sday+1),] # this Sdat get big profit
          PriHigh = max(Sdat$HIGH) *.9 + min(Sdat$LOW) *.1; PriLow = max(Sdat$HIGH) *.1 + min(Sdat$LOW) *.9
          Close = datK.old[Sday+1,'CLOSE']
          # set buy condition
          ChangeRateH = (PriHigh - Close)/Close * 100; ChangeRateL = (PriLow - Close)/Close * 100
          sdJ1 = datK.old[Sday+1,'J'] - datK.old[Sday+2,'J'];sdJ2 = datK.old[Sday+2,'J'] - datK.old[Sday+3,'J']
          sdJ1 = ifelse(!anyNA(sdJ1),sdJ1,0); sdJ2 = ifelse(!anyNA(sdJ2),sdJ2,0); 
          dayPriT <- PriLow <= (max(datK.old$HIGH[(Sday+1):(Sday+mn)]) *.2 + min(datK.old$LOW[(Sday+1):(Sday+mn)]) *.8)
          dayPriT <- ifelse(!is.na(dayPriT),dayPriT,FALSE)
          # test buy in new stocks
          if (sdJ1 > sdJ2 & FinalHold==0 & dayPriT & Sdat$J < 90) {
            # cat(paste0('bandWeek: ',d,'| Got true buy env of ', Scode,'\n\tBuyDay: ',Sdat$Date[1],'\n'))
            if (ChangeRateL <= -8) {
              # cat('\tBuying: ChangeRate <= -7 and AddholdNum = 1000\n')
              HoldStoNum = 1000 + baseHold
              money = money - PriLow * HoldStoNum
            } else if (ChangeRateL <= -5 & ChangeRateL > -8) {
              # cat('\tBuying: -3 <= ChangeRate < -7 and AddholdNum = 500\n')
              HoldStoNum = 700 + baseHold
              money = money - PriLow * HoldStoNum
            } else if (ChangeRateL <= -2 & ChangeRateL > -5) {
              # cat('\tBuying: -1 <= ChangeRate < -3 and AddholdNum = 200\n')
              HoldStoNum = 500 + baseHold
              money = money - PriLow * HoldStoNum
            } else if (ChangeRateL <= 1 & ChangeRateL > -2) {
              # cat('\tBuying: -1 <= ChangeRate < -3 and AddholdNum = 200\n')
              HoldStoNum = 200 + baseHold
              money = money - PriLow * HoldStoNum
            } else if (PriLow < Close) {
              # cat('\tBuying: PriLow < Close and AddholdNum = 500\n')
              HoldStoNum = 300 + baseHold
              money = money - PriLow * HoldStoNum
            }
            FinalHold = FinalHold + HoldStoNum
          }
          if (FinalHold > 0) {
            BuyDate = Sdat$Date; Hvalue1 = Sdat$HIGH * 1.01; Lvalue1 = Sdat$LOW
            BS.dat = data.frame(bandDate = d, BS.Date = BuyDate, buyN = FinalHold, sellN = 0, price = PriLow, 
                                FinalHold = FinalHold, money = money, profit = '.', 
                                Hday ='.', Pro.day = '.', tags = 'new')
            break()
          }
        }
      }
      # test buy or sell after buying new stocks
      for (b in 1:MaxHoldDays) {
        ## set and test buy/sell condition in second day
        Hday = Sday - b
        if (Hday > 0 & FinalHold != 0) {
          Hdat = datK.old[c(Hday),]; Hdat$Date = as.character(Hdat$Date) 
          PriHigh = max(Hdat$HIGH) *.9 + min(Hdat$LOW) *.1; PriLow = max(Hdat$HIGH) *.1 + min(Hdat$LOW) *.9
          Close = datK.old[Hday+1,'CLOSE']
          # set buy condition
          ChangeRateH = (PriHigh - Close)/Close * 100; ChangeRateL = (PriLow - Close)/Close * 100
          sdJ1 = datK.old[Hday+1,'J'] - datK.old[Hday+2,'J'];sdJ2 = datK.old[Hday+2,'J'] - datK.old[Hday+3,'J']
          sdJ1 = ifelse(!anyNA(sdJ1),sdJ1,0); sdJ2 = ifelse(!anyNA(sdJ2),sdJ2,0); 
          dayPriT <- PriHigh >= (max(datK.old$HIGH[(Hday+1):(Hday+mn)]) *.8 + min(datK.old$LOW[(Hday+1):(Hday+mn)]) *.2)
          dayPriT <- ifelse(!is.na(dayPriT),dayPriT,FALSE)
          # test PriHigh and PriLow 
          if (sdJ1 > sdJ2) {
            # test to abort with limit profit before buy new
            if (money + FinalHold * PriHigh - 50000 > Proless) {
              # cat('\t|GoSell.all on day',Hdat$Date[1],'\n')
              money = money + PriHigh * FinalHold; gain = round(money - 50000,2)
              Hdays = as.numeric(as.Date(Hdat$Date[1]) - as.Date(BS.dat$BS.Date[1]))
              BS.dat.i = data.frame(bandDate = '.', BS.Date = Hdat$Date[1], buyN = 0, sellN = FinalHold,  price = PriHigh, 
                                    FinalHold = 0, money = money, profit = gain, 
                                    Hday = Hdays, Pro.day = round(gain / Hdays, 2), tags = 'Pro.cls')
              BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
              FinalHold = 0; break()
            }
            # test buy
            # cat(paste0('\t|testBuyorSell...on day: ',Hdat$Date[1],'\n'))
            if (ChangeRateL <= -8 & FinalHold != 0  & Hday > 1) {
              # cat('\t|GoBuy.1000 on day',Hdat$Date[1],'\n')
              FinalHold = FinalHold + 1000
              money = money - PriLow * 1000
              BS.dat.i = data.frame(bandDate = '.', BS.Date = Hdat$Date[1], buyN = 1000, sellN = 0,  price = PriLow, 
                                    FinalHold = FinalHold, money = money, profit = '.', 
                                    Hday = '.', Pro.day = '.', tags = 'plus')
              BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
            } else if (ChangeRateL > -8 & ChangeRateL <= -6 & FinalHold != 0  & Hday > 1) {
              # cat('\t|GoBuy.700 on day',Hdat$Date[1],'\n')
              FinalHold = FinalHold + 700
              money = money - PriLow * 700
              BS.dat.i = data.frame(bandDate = '.', BS.Date = Hdat$Date[1], buyN = 700, sellN = 0,  price = PriLow, 
                                    FinalHold = FinalHold, money = money, profit = '.', 
                                    Hday = '.', Pro.day = '.', tags = 'plus')
              BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
            } else if (ChangeRateL > -6 & ChangeRateL <= -4 & FinalHold != 0  & Hday > 1) {
              # cat('\t|GoBuy.500 on day',Hdat$Date[1],'\n')
              FinalHold = FinalHold + 500
              money = money - PriLow * 500
              BS.dat.i = data.frame(bandDate = '.', BS.Date = Hdat$Date[1], buyN = 500, sellN = 0,  price = PriLow, 
                                    FinalHold = FinalHold, money = money, profit = '.', 
                                    Hday = '.', Pro.day = '.', tags = 'plus')
              BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
            } else if (ChangeRateL > -4 & ChangeRateL <= -2 & FinalHold != 0  & Hday > 1) {
              # cat('\t|GoBuy.200 on day',Hdat$Date[1],'\n')
              FinalHold = FinalHold + 200
              money = money - PriLow * 200
              BS.dat.i = data.frame(bandDate = '.', BS.Date = Hdat$Date[1], buyN = 200, sellN = 0,  price = PriLow, 
                                    FinalHold = FinalHold, money = money, profit = '.', 
                                    Hday = '.', Pro.day = '.', tags = 'plus')
              BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
            } 
            # test sell
            if ((ChangeRateH >= 1 & ChangeRateH < 3) | dayPriT & FinalHold != 0) {
              # cat('\t|GoSell.200 on day',Hdat$Date[1],'\n')
              minusCount = ifelse(FinalHold > 200, 200, 0)
              FinalHold = FinalHold - minusCount
              money = money + PriHigh * minusCount
              BS.dat.i = data.frame(bandDate = '.', BS.Date = Hdat$Date[1], buyN = 0, sellN = minusCount,  price = PriHigh, 
                                    FinalHold = FinalHold, money = money, profit='.',
                                    Hday ='.', Pro.day = '.', tags = 'minus')
              BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
            } else if (ChangeRateH >= 3 & ChangeRateH < 5 & FinalHold != 0) {
              # cat('\t|GoSell.500 on day',Hdat$Date[1],'\n')
              minusCount = ifelse(FinalHold > 500, 500, FinalHold - 100)
              FinalHold = FinalHold - minusCount
              money = money + PriHigh * minusCount
              BS.dat.i = data.frame(bandDate = '.', BS.Date = Hdat$Date[1], buyN = 0, sellN = minusCount,  price = PriHigh, 
                                    FinalHold = FinalHold, money = money, profit='.',
                                    Hday ='.', Pro.day = '.', tags = 'minus')
              BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
            } else if (ChangeRateH >= 5 & ChangeRateH < 7 & FinalHold != 0) {
              # cat('\t|GoSell.700 on day',Hdat$Date[1],'\n')
              minusCount = ifelse(FinalHold > 700, 700, FinalHold - 100)
              FinalHold = FinalHold - minusCount
              money = money + PriHigh * minusCount
              BS.dat.i = data.frame(bandDate = '.', BS.Date = Hdat$Date[1], buyN = 0, sellN = minusCount, price = PriHigh, 
                                    FinalHold = FinalHold, money = money, profit='.',
                                    Hday ='.', Pro.day = '.', tags = 'minus')
              BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
            } else if (ChangeRateH >= 7 & FinalHold != 0) {
              # cat('\t|GoSell.1000 on day',Hdat$Date[1],'\n')
              minusCount = ifelse(FinalHold > 1000, 1000, FinalHold - 100)
              FinalHold = FinalHold - minusCount
              money = money + PriHigh * minusCount
              BS.dat.i = data.frame(bandDate = '.', BS.Date = Hdat$Date[1], buyN = 0, sellN = minusCount,  price = PriHigh, 
                                    FinalHold = FinalHold, money = money, profit='.',
                                    Hday ='.', Pro.day = '.', tags = 'minus')
              BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
            }
            # Unknown place
            if (datK.old[1,'J'] < 50 & FinalHold != 0 & Hday > 1) {
              Close = datK.old$CLOSE[1]; Close3 = datK.old$CLOSE[3]; Close7 = datK.old$CLOSE[7]
              ChangeRate3 = (Close - Close7)/Close7 * 100
              ChangeRate7 = (Close - Close7)/Close7 * 100
              ChangeRateTest = (ChangeRate3 > -2 & ChangeRate7 < -5 & min(datK.old$CLOSE[1:3]) <= min(datK.old$CLOSE[4:25]))
              bandCrovalue = bandCrotest(Scode,Type = 'sting', bandFrom = 10, bandNum = 4, status = T)
              if (ChangeRateTest | bandCrovalue) {
                if (ChangeRateL <= -8) {
                  # cat('\t|GoBuy.1000\n')
                  FinalHold = FinalHold + 1000
                  money = money - PriLow * 1000
                  BS.dat.i = data.frame(bandDate = '.', BS.Date = Hdat$Date[1], buyN = 1000, sellN = 0, price = PriLow, 
                                        FinalHold = FinalHold, money = money, profit='.',
                                        Hday='.', Pro.day = '.', tags = 'low|cro' )
                  BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
                } else if (ChangeRateL <= -5 & ChangeRateL > -8) {
                  # cat('\t|GoBuy.700\n')
                  FinalHold = FinalHold + 700
                  money = money - PriLow * 700
                  BS.dat.i = data.frame(bandDate = '.', BS.Date = Hdat$Date[1], buyN = 700, sellN = 0, price = PriLow, 
                                        FinalHold = FinalHold, money = money, profit='.',
                                        Hday='.', Pro.day = '.', tags = 'low|cro' )
                  BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
                } else if (ChangeRateL <= -2 & ChangeRateL > -5) {
                  # cat('\t|GoBuy.500\n')
                  FinalHold = FinalHold + 500
                  money = money - PriLow * 500
                  BS.dat.i = data.frame(bandDate = '.', BS.Date = Hdat$Date[1], buyN = 500, sellN = 0, price = PriLow, 
                                        FinalHold = FinalHold, money = money, profit='.',
                                        Hday='.', Pro.day = '.', tags = 'low|cro' )
                  BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
                } else if (ChangeRateL > -2 & ChangeRateL < 1) {
                  # cat('\t|GoBuy.300\n')
                  FinalHold = FinalHold + 200
                  money = money - PriLow * 200
                  BS.dat.i = data.frame(bandDate = '.', BS.Date = Hdat$Date[1], buyN = 200, sellN = 0, price = PriLow, 
                                        FinalHold = FinalHold, money = money, profit='.',
                                        Hday='.', Pro.day = '.', tags = 'low|cro' )
                  BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
                }
              }
            }
          }
        }
      }
      if (FinalHold > 0) {
        money = money + PriHigh * FinalHold; gain = round(money - 50000,2)
        Hdays = as.numeric(as.Date(Hdat$Date[1]) - as.Date(BS.dat$BS.Date[1]))
        BS.dat.i = data.frame(bandDate = '.', BS.Date = Hdat$Date[1], buyN = 0, sellN = FinalHold,  price = PriHigh, 
                              FinalHold = 0, money = money , profit = gain , 
                              Hday = Hdays, Pro.day = round(gain / Hdays, 2), tags = 'End.cls')
        BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
      }
      if (money != 50000) {
        # cat(paste0('\tFinal got money with ',money,' at bandWeek ',d,' on day of ',Hdat$Date[1],'\n\t',paste0(rep('-',73),collapse = ''),'\n'))
        profit = profit + money - 50000
        profit.i = money - 50000
        SellDate = Hdat$Date[1]; Hvalue2 = Hdat$HIGH[1] * 1.02
        Buydat.i <- data.frame(name1 = Lvalue1, xAxis1 = BuyDate, yAxis1 = Hvalue1,
                               name2 = Hvalue2, xAxis2 = SellDate, yAxis2 = Hvalue2,value = profit.i)
        Buydat <- rbind.data.frame(Buydat, Buydat.i) # for animation mark lines 
        #
        BS.datT = rbind.data.frame(BS.datT, BS.dat)
      }
    }
    #
    cat(paste0('Finally got ',length(unique(BS.datT$bandDate)) - 1,' trading band: '))
    print(knitr::kable(BS.datT))
    # total profit
    cat(paste0('\tProfit of ',Scode,' was ', round(profit,2),'\n'))
    # plot 
    if (plot & length(Buydat) > 0) {
      if (nrow(Buydat) > 1) {
        for (n in 2:nrow(Buydat)) {
          if (Buydat$xAxis1[n] == Buydat$xAxis1[n-1]) {
            Buydat$yAxis1[n] = Buydat$yAxis1[n-1] * 1.01
            Buydat$value[n] = Buydat$value[n] + Buydat$value[n-1]
            Buydat$value[n-1] = NA
          }
        }
      }
      SpyKplot(Scode,type = 'sting',bandTestres = bandRes,viewNum = viewNum) %>%
        addML(data = Buydat, symbolSize = c(1, 1), mode = 'override', 
              effect = list(show = T,color = 'blue',loop = TRUE, period = 60, scaleSize = 1))
    } else if (plot) {
      SpyKplot(Scode,type = 'sting',bandTestres = bandRes,viewNum = viewNum)}
  }
}
```

###### *Just report front 10 stocks, un-reported were: 300797, 000603, 600476, 300541, 300566, 300232, 002119, 002953, 300381, 300796, 002268, 300183, 002868, 000712, 002036, 603688, 300428, 300627, 600373, 002389, 603619, 603995, 002903, 600410, 300480, 603507, 300467, 603727, 002045, 603848, 000038, 300809, 300648, 002655, 002524, 002474, 600647, 000998, 300489, 603037, 000887, 603536, 600131, 600037, 603839, 603718, 600305, 600359, 603268, 600137, 300503, 002840*

## Stock trading footsteps of 600893

```{r, echo=TRUE}
bandTest = bandCrotest('600893', bandFrom = 30, bandNum = 4)
bandProfit('600893', bandRes = bandTest, plot = T, viewNum = 60)
StoQplot('600893', plot = c('StoIO'), viewNum = 60)
StoQplot('600893', plot = c('StoVP'), viewNum = 60)
tradePlot('600893')
```

## Stock trading footsteps of 603032

```{r, echo=TRUE}
bandTest = bandCrotest('603032', bandFrom = 30, bandNum = 4)
bandProfit('603032', bandRes = bandTest, plot = T, viewNum = 60)
StoQplot('603032', plot = c('StoIO'), viewNum = 60)
StoQplot('603032', plot = c('StoVP'), viewNum = 60)
tradePlot('603032')
```

## Stock trading footsteps of 603959

```{r, echo=TRUE}
bandTest = bandCrotest('603959', bandFrom = 30, bandNum = 4)
bandProfit('603959', bandRes = bandTest, plot = T, viewNum = 60)
StoQplot('603959', plot = c('StoIO'), viewNum = 60)
StoQplot('603959', plot = c('StoVP'), viewNum = 60)
tradePlot('603959')
```

## Stock trading footsteps of 002142

```{r, echo=TRUE}
bandTest = bandCrotest('002142', bandFrom = 30, bandNum = 4)
bandProfit('002142', bandRes = bandTest, plot = T, viewNum = 60)
StoQplot('002142', plot = c('StoIO'), viewNum = 60)
StoQplot('002142', plot = c('StoVP'), viewNum = 60)
tradePlot('002142')
```

## Stock trading footsteps of 000016

```{r, echo=TRUE}
bandTest = bandCrotest('000016', bandFrom = 30, bandNum = 4)
bandProfit('000016', bandRes = bandTest, plot = T, viewNum = 60)
StoQplot('000016', plot = c('StoIO'), viewNum = 60)
StoQplot('000016', plot = c('StoVP'), viewNum = 60)
tradePlot('000016')
```

## Stock trading footsteps of 600114

```{r, echo=TRUE}
bandTest = bandCrotest('600114', bandFrom = 30, bandNum = 4)
bandProfit('600114', bandRes = bandTest, plot = T, viewNum = 60)
StoQplot('600114', plot = c('StoIO'), viewNum = 60)
StoQplot('600114', plot = c('StoVP'), viewNum = 60)
tradePlot('600114')
```

## Stock trading footsteps of 300046

```{r, echo=TRUE}
bandTest = bandCrotest('300046', bandFrom = 30, bandNum = 4)
bandProfit('300046', bandRes = bandTest, plot = T, viewNum = 60)
StoQplot('300046', plot = c('StoIO'), viewNum = 60)
StoQplot('300046', plot = c('StoVP'), viewNum = 60)
tradePlot('300046')
```

## Stock trading footsteps of 603558

```{r, echo=TRUE}
bandTest = bandCrotest('603558', bandFrom = 30, bandNum = 4)
bandProfit('603558', bandRes = bandTest, plot = T, viewNum = 60)
StoQplot('603558', plot = c('StoIO'), viewNum = 60)
StoQplot('603558', plot = c('StoVP'), viewNum = 60)
tradePlot('603558')
```

## Stock trading footsteps of 600460

```{r, echo=TRUE}
bandTest = bandCrotest('600460', bandFrom = 30, bandNum = 4)
bandProfit('600460', bandRes = bandTest, plot = T, viewNum = 60)
StoQplot('600460', plot = c('StoIO'), viewNum = 60)
StoQplot('600460', plot = c('StoVP'), viewNum = 60)
tradePlot('600460')
```

## Stock trading footsteps of 002971

```{r, echo=TRUE}
bandTest = bandCrotest('002971', bandFrom = 30, bandNum = 4)
bandProfit('002971', bandRes = bandTest, plot = T, viewNum = 60)
StoQplot('002971', plot = c('StoIO'), viewNum = 60)
StoQplot('002971', plot = c('StoVP'), viewNum = 60)
tradePlot('002971')
```

Note: reports updated on 2020-05-27