---
title: THStradingReport
author: Himawork
date: '2020-05-20'
slug: THStradingReport_2020-05-20
categories:
  - HTML
tags:
  - Reports
  - Trade
---

```{r Load_Functions, echo=FALSE, warning=FALSE}
# load packages and functions ----
suppressMessages({library(rvest); library(recharts)})
# range band cross rate test, generate 'bandTest' for SpyKplot()
bandCrotest <- function(Scode,Type = 'sting', range = c(50, 60), bandFrom = 30, bandNum = 4, K_type=c('dailyK')) {
  datK.old = readRDS('e:/tess/SpySto.RDS')[[Type]][[Scode]][[K_type]]; bandRange = bandNum -1; bandRes = NULL
  if (length(datK.old$Date) < bandFrom) {
    print('bandFrom out of datK boundary, use default length of datK.')
    bandFrom = length(datK.old$Date)
  }
  # 
  for (b in bandFrom:(bandNum+1)) {
    bandMin = max(datK.old$HIGH[b:(b-bandRange)]) * range[1]/100 + min(datK.old$LOW[b:(b-bandRange)]) * (1 - range[1]/100)
    bandMax = max(datK.old$HIGH[b:(b-bandRange)]) * range[2]/100 + min(datK.old$LOW[b:(b-bandRange)]) * (1 - range[2]/100)
    NumCro<- length(grep('TRUE',(datK.old$LOW[b:(b-bandRange)] < bandMin & datK.old$HIGH[b:(b-bandRange)] > bandMax)))
    bandDate = datK.old$Date[b-bandRange];
    if (NumCro >= ceiling(bandNum * 0.6)) {
      bandTest = TRUE
      # cat(paste0(bandDate,'| bandMin: ',bandMin,'; bandMax: ',bandMax,'; NumCro: ',NumCro,'\n'))
      # cat(paste0(c(datK.old$LOW[b:(b-bandRange)] < bandMin & datK.old$HIGH[b:(b-bandRange)] > bandMax)));cat('\n')
      Hvalue = readRDS('e:/tess/SpySto.RDS')[[Type]][[Scode]][['dailyK']]$HIGH[which(readRDS('e:/tess/SpySto.RDS')[[Type]][[Scode]][['dailyK']][,'Date'] == bandDate)]
      if (length(Hvalue) !=1) {Hvalue=bandMax}
      banddat = data.frame(Date = bandDate, Test = bandTest, NumCro = NumCro, High = Hvalue * 1.01)
      bandRes = rbind.data.frame(bandRes, banddat)
    } # else {cat(paste0(bandDate,'|\n'))}
  }
  return(bandRes)
}
# plot K-kines
SpyKplot = function(Scode = '', type = c('sting'), bandTestres = bandTest, subtype = c('dailyK'), 
                    plot = c('K-line','MACD','KDJ'), viewNum = 30) {
  BuyScodeNum = names(readRDS('e:/tess/SpySto.RDS')[[type]])
  if (Scode %in% BuyScodeNum) {
    dataK = readRDS('e:/tess/SpySto.RDS')[[type]][[Scode]][[subtype]][1:viewNum,]
    dataK = na.omit(dataK[duplicated(dataK$Date)==F,])
    if (nrow(dataK) < viewNum) {
      viewNum <- nrow(dataK)
      cat(paste0('ViewNum out of boundary. Use default ',nrow(dataK), ' nrows of dataK.\n'))
    }
    # change theme
    if (subtype=='dailyK') {
      themeK = 'default'
    } else if (subtype=='weeklyK') {
      themeK = 'helianthus'
    } else if (subtype=='monthlyK') {
      themeK = 'macarons'
    } 
    # K line
    if (plot == 'K-line') {
      bandres = bandTestres; names(bandres) = c('xAxis','value','name','yAxis')
      Kplot <-  echartr(dataK, as.character(Date), c('OPEN', 'CLOSE', 'LOW', 'HIGH'), type='k') %>%  
        # set_grid(width = 800, height = 300,widget = 'pane') %>%
        setXAxis(name='', axisLabel=list(rotate=45,textStyle=list(fontSize = 8.5))) %>%
        set_theme(width = 960,height = 300,theme = themeK)  %>%  set_legend(show = F)%>% 
        setYAxis(name="Price") %>% setToolbox(show = F,controls = c("dataZoom", "restore"), pos = 9)%>% 
        setTitle(subtitle =  paste0(subtype,'_',plot, ' of ', Scode), pos =12,
                 sublink = paste0("http://stockpage.10jqka.com.cn/", Scode)) %>%
        setTooltip(show=T,textStyle = list(fontSize=8.5,align='left',baseline='middle')) %>% 
        addMP(data = bandres,symbol = 'pin',symbolSize =3,effect = list(show = F,color='green')) %>% 
        setDataZoom(fill=rgba(c(col2rgb('lightgreen'), 0.2)), handle=rgba(c(col2rgb('darkgreen'), 0.5)))
      # MACD line
    } else if (plot == 'MACD') {
      MACD.melt = data.table::melt(dataK,id ='Date',measure=c('MACD','DIFF','DEA'), variable.factor = F)
      Kplot = echartr(MACD.melt, as.character(Date),value,variable, type='line') %>% 
        set_theme(width = 960,height = 300,theme = themeK)  %>%  
        setTooltip(show=T,textStyle = list(fontSize=8.5,align='left',baseline='middle'))  %>%
        setToolbox(show = F) %>%  setTitle(subtitle = paste0(subtype,'-',plot),title = Scode,pos =12) %>%
        setXAxis(name='date', axisLabel=list(rotate=45,textStyle=list(fontSize = 8.5)))%>% 
        setDataZoom(fill=rgba(c(col2rgb('lightgreen'), 0.2)), handle=rgba(c(col2rgb('darkgreen'), 0.5)))
      # KDJ line
    } else if (plot == 'KDJ') {
      KDJ.melt = data.table::melt(dataK,id ='Date',measure=c('K','D','J'), variable.factor = F)
      Kplot =  echartr(KDJ.melt, as.character(Date),value,variable, type='line',subtype = c(rep('dotted',3),'smooth')) %>% 
        setTooltip(show=T,textStyle = list(fontSize=8.5,align='left',baseline='middle')) %>%
        set_theme(width = 960,height = 300,theme = themeK)  %>%  
        setToolbox(show = F) %>%  setTitle(subtitle =  paste0(subtype,'-',plot),title = Scode,pos =12) %>%
        setXAxis(name='date', axisLabel=list(rotate=45,textStyle=list(fontSize = 8.5))) %>% 
        setDataZoom(fill=rgba(c(col2rgb('lightgreen'), 0.2)), handle=rgba(c(col2rgb('darkgreen'), 0.5)))
    } else print('None plot can drawing...')
    return(Kplot)
  } else print(paste0(Scode,' is not in subdata of ',type))
}
# plot stock trading details
StoQplot = function(Scode = '', type = c('sting'), plot = c('StoIO', 'StoVP'), viewNum = 30) {
  BuyScodeNum = names(readRDS('e:/tess/SpySto.RDS')[[type]])
  if (Scode %in% BuyScodeNum) {
    Qplot.dat = readRDS('e:/tess/SpySto.RDS')[['sting']][[Scode]][['CStoDetail']]
    if (nrow(Qplot.dat) < viewNum) {
      viewNum <- nrow(Qplot.dat)
      Qplot.dat = Qplot.dat[1:viewNum,]
      cat(paste0('ViewNum out of boundary. Use default ',nrow(Qplot.dat), ' nrows of Qplot.dat.\n'))
    }
    if (plot == "StoIO") {
      # stock in and out
      Qplot.dat = na.omit(Qplot.dat[duplicated(Qplot.dat$compTime)==F,c(1,10:15)])
      dat.melt = data.table::melt(Qplot.dat,id ='compTime',measure=c('StoIN.max','StoIN.mid','StoIN.min'))
      dat.melt2 = data.table::melt(Qplot.dat,id ='compTime',measure=c('StoOUT.max','StoOUT.mid','StoOUT.min'))
      dat.melt2$value = -dat.melt2$value # ; dat.melt$class = 'StoIN'; dat.melt2$class = 'StoOUT'
      Qplot = echartr(rbind.data.frame(dat.melt, dat.melt2), as.character(compTime), value, variable, type='area') %>%
        setTitle(subtitle = "Trading quantity: StoOUT vs. StoIN", pos = 12, 
                 sublink = paste0("http://stockpage.10jqka.com.cn/", Scode)) %>%  
        setXAxis(name = "", axisLabel = list(rotate = 30)) %>% setYAxis(name = "万元") %>%  
        setTooltip(show=T,textStyle = list(fontSize=8.5,align='left',baseline='middle')) %>%
        set_theme(width = 960,height = 480) %>% setToolbox(show = T,controls = c("dataZoom", "restore"), pos = 1)
    } else if (plot == "StoVP") {
      # gauge plot of stock trading change
      Qplot.dat = na.omit(Qplot.dat[duplicated(Qplot.dat$compTime)==F,c(1,8,9)])
      BD.dat = rbind.data.frame(data.frame(value = Qplot.dat$振幅, class = 'Vib/%'),
                                data.frame(value = Qplot.dat$换手, class = 'Tra/%'))
      BD.dat$date = Qplot.dat$compTime; BD.dat$value = round(BD.dat$value, 2)
      Qplot = echartr(BD.dat, x = class, y = value, facet = class, t = as.character(date), type='gauge') %>%
        set_theme(width = 960,height = 480, theme = 'shine') %>% setToolbox(show = F) %>% setTooltip(show = F) %>% 
        set_legend(show = F) %>% setTimeline(label = list(rotate = 30), symbol='emptyCircle' , y2=60) %>% 
        setTitle(subtitle = "振幅（%）和换手率（%）", pos = 12,
                 sublink = paste0("http://stockpage.10jqka.com.cn/", Scode)) 
    }
    return(Qplot)
  } else print(paste0(Scode,' is not in subdata of ',type))
}
# calculate profit
bandProfit <- function(Scode, bandRes = '', MaxHoldDays = 10, plot = F, mn = 7, baseHold = 0, 
                       Maxband = 1, viewNum = 30) {
  datK.old = na.omit(readRDS('e:/tess/SpySto.RDS')[['sting']][[Scode]][['dailyK']])
  if (length(bandRes) < 1) {stop(print(paste0('No profit band of stock ',Scode)))}
  bandRes$Date = as.character(bandRes$Date); profit = 0; MaxTestDays = Maxband * 5; 
  Buydat = NULL; BS.dat = NULL; BS.datT = NULL
  for (d in bandRes$Date) {
    FinalHold = 0; HoldStoNum = 0; money = 50000; 
    for (m in 1:MaxTestDays) {
      Sday = which(datK.old$Date==d) - m
      Sday <- ifelse(length(Sday) ==1,Sday,0)
      ## test buy env and buying new stocks
      if (Sday > 1) {
        Sdat = datK.old[c(Sday),]; Sdat$Date = as.character(Sdat$Date) 
        # Sdat = datK.old[c(Sday,Sday+1),] # this Sdat get big profit
        PriHigh = max(Sdat$HIGH) *.9 + min(Sdat$LOW) *.1; PriLow = max(Sdat$HIGH) *.1 + min(Sdat$LOW) *.9
        Close = datK.old[Sday+1,'CLOSE']
        # set buy condition
        ChangeRateH = (PriHigh - Close)/Close * 100; ChangeRateL = (PriLow - Close)/Close * 100
        sdJ1 = datK.old[Sday+1,'J'] - datK.old[Sday+2,'J'];sdJ2 = datK.old[Sday+2,'J'] - datK.old[Sday+3,'J']
        sdJ3 = datK.old[Sday+3,'J'] - datK.old[Sday+4,'J'];sdJ4 = datK.old[Sday+4,'J'] - datK.old[Sday+5,'J']
        sdJ1 = ifelse(!anyNA(sdJ1),sdJ1,0); sdJ2 = ifelse(!anyNA(sdJ2),sdJ2,0); 
        sdJ3 = ifelse(!anyNA(sdJ3),sdJ3,0); sdJ4 = ifelse(!anyNA(sdJ4),sdJ4,0); 
        dayPriT <- PriLow <= (max(datK.old$HIGH[(Sday+1):(Sday+mn)]) *.2 + min(datK.old$LOW[(Sday+1):(Sday+mn)]) *.8)
        dayPriT <- ifelse(!is.na(dayPriT),dayPriT,FALSE)
        # test buy in new stocks
        if (sdJ1 > sdJ2 & FinalHold==0 & dayPriT & Sdat$J < 90) {
          # cat(paste0('bandWeek: ',d,'| Got true buy env of ', Scode,'\n\tBuyDay: ',Sdat$Date[1],'\n'))
          if (ChangeRateL <= -7) {
            # cat('\tBuying: ChangeRate <= -7 and AddholdNum = 1000\n')
            HoldStoNum = 1000 + baseHold
            money = money - PriLow * HoldStoNum
          } else if (ChangeRateL <= -3 & ChangeRateL > -7) {
            # cat('\tBuying: -3 <= ChangeRate < -7 and AddholdNum = 500\n')
            HoldStoNum = 500 + baseHold
            money = money - PriLow * HoldStoNum
          } else if (ChangeRateL <= -1 & ChangeRateL > -3) {
            # cat('\tBuying: -1 <= ChangeRate < -3 and AddholdNum = 200\n')
            HoldStoNum = 200 + baseHold
            money = money - PriLow * HoldStoNum
          } else if (PriLow < Close) {
            # cat('\tBuying: PriLow < Close and AddholdNum = 500\n')
            HoldStoNum = 500 + baseHold
            money = money - PriLow * HoldStoNum
          }
          FinalHold = FinalHold + HoldStoNum
        }
        if (FinalHold > 0) {
          BuyDate = Sdat$Date; Hvalue1 = Sdat$HIGH * 1.01; Lvalue1 = Sdat$LOW
          BS.dat = data.frame(bandDate = d, BS.Date = BuyDate, buyN = FinalHold, sellN = 0, profit = NA)
          break()
        }
      }
    }
    # test buy or sell after buying new stocks
    for (b in 1:MaxHoldDays) {
      ## set and test buy/sell condition in second day
      Hday = Sday - b
      if (Hday > 0 & FinalHold != 0) {  
        Hdat = datK.old[c(Hday),]; Hdat$Date = as.character(Hdat$Date) 
        PriHigh = max(Hdat$HIGH) *.9 + min(Hdat$LOW) *.1; PriLow = max(Hdat$HIGH) *.1 + min(Hdat$LOW) *.9
        Close = datK.old[Hday+1,'CLOSE']
        # set buy condition
        ChangeRateH = (PriHigh - Close)/Close * 100; ChangeRateL = (PriLow - Close)/Close * 100
        sdJ1 = datK.old[Hday+1,'J'] - datK.old[Hday+2,'J'];sdJ2 = datK.old[Hday+2,'J'] - datK.old[Hday+3,'J']
        sdJ1 = ifelse(!anyNA(sdJ1),sdJ1,0); sdJ2 = ifelse(!anyNA(sdJ2),sdJ2,0); 
        dayPriT <- PriHigh >= (max(datK.old$HIGH[(Hday+1):(Hday+mn)]) *.8 + min(datK.old$LOW[(Hday+1):(Hday+mn)]) *.2)
        dayPriT <- ifelse(!is.na(dayPriT),dayPriT,FALSE)
        # test PriHigh and PriLow 
        if (sdJ1 > 0 & sdJ2 > 0) {
          # cat(paste0('\t|testBuyorSell...on day: ',Hdat$Date[1],'\n'))
          if (ChangeRateL <= -8 & FinalHold != 0  & Hday > 1) {
            # cat('\t|GoBuy.1000 on day',Hdat$Date[1],'\n')
            FinalHold = FinalHold + 1000
            money = money - PriLow * 1000
            BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 1000, sellN = 0, profit = NA)
            BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
          } else if (ChangeRateL > -8 & ChangeRateL <= -6 & FinalHold != 0  & Hday > 1) {
            # cat('\t|GoBuy.700 on day',Hdat$Date[1],'\n')
            FinalHold = FinalHold + 700
            money = money - PriLow * 700
            BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 700, sellN = 0, profit = NA)
            BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
          } else if (ChangeRateL > -6 & ChangeRateL <= -4 & FinalHold != 0  & Hday > 1) {
            # cat('\t|GoBuy.500 on day',Hdat$Date[1],'\n')
            FinalHold = FinalHold + 500
            money = money - PriLow * 500
            BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 500, sellN = 0, profit = NA)
            BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
          } else if (ChangeRateL > -4 & ChangeRateL <= -2 & FinalHold != 0  & Hday > 1) {
            # cat('\t|GoBuy.200 on day',Hdat$Date[1],'\n')
            FinalHold = FinalHold + 200
            money = money - PriLow * 200
            BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 200, sellN = 0, profit = NA)
            BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
            # test sell
          } else if (ChangeRateH >= 1 & ChangeRateH < 3 & FinalHold >= 200) {
            # cat('\t|GoSell.200 on day',Hdat$Date[1],'\n')
            FinalHold = FinalHold - 200
            money = money + PriHigh * 200
            if (FinalHold == 0) {
              BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 0, sellN = 200, profit = money - 50000)
            } else {
              BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 0, sellN = 200, profit = NA)
            }
            BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
          } else if (ChangeRateH >= 3 & ChangeRateH < 5 & FinalHold >= 500) {
            # cat('\t|GoSell.500 on day',Hdat$Date[1],'\n')
            FinalHold = FinalHold - 500
            money = money + PriHigh * 500
            if (FinalHold == 0) {
              BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 0, sellN = 500, profit = money - 50000)
            } else {
              BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 0, sellN = 500, profit = NA)
            }
            BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
          } else if (ChangeRateH >= 5 & ChangeRateH < 7 & FinalHold >= 700) {
            # cat('\t|GoSell.700 on day',Hdat$Date[1],'\n')
            FinalHold = FinalHold - 700
            money = money + PriHigh * 700
            if (FinalHold == 0) {
              BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 0, sellN = 700, profit = money - 50000)
            } else {
              BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 0, sellN = 700, profit = NA)
            }
            BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
          } else if (ChangeRateH >= 7 & ChangeRateH < 9 & FinalHold >= 1000) {
            # cat('\t|GoSell.1000 on day',Hdat$Date[1],'\n')
            FinalHold = FinalHold - 1000
            money = money + PriHigh * 1000
            if (FinalHold == 0) {
              BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 0, sellN = 1000, profit = money - 50000)
            } else {
              BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 0, sellN = 1000, profit = NA)
            }
            BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
          } else if (ChangeRateH >= 9 | dayPriT) {
            # cat('\t|GoSell.all on day',Hdat$Date[1],'\n')
            money = money + PriHigh * FinalHold
            BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 0, sellN = FinalHold, profit = money - 50000)
            BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
            FinalHold = 0
          }
        }
      }
    }
    if (FinalHold > 0) {
      money = money + PriHigh * FinalHold; 
      BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 0, sellN = FinalHold, profit = money - 50000)
      BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
    }
    if (money != 50000) {
      # cat(paste0('\tFinal got money with ',money,' at bandWeek ',d,' on day of ',Hdat$Date[1],'\n\t',paste0(rep('-',73),collapse = ''),'\n'))
      profit = profit + money - 50000
      profit.i = money - 50000
      SellDate = Hdat$Date[1]; Hvalue2 = Hdat$HIGH[1] * 1.02
      Buydat.i <- data.frame(name1 = Lvalue1, xAxis1 = BuyDate, yAxis1 = Hvalue1,
                             name2 = Hvalue2, xAxis2 = SellDate, yAxis2 = Hvalue2,value = profit.i)
      Buydat <- rbind.data.frame(Buydat, Buydat.i)
      #
      BS.datT = rbind.data.frame(BS.datT, BS.dat)
    }
  }
  #
  cat(paste0('Finally got ',length(unique(BS.datT$bandDate)),' trading band: '))
  print(knitr::kable(BS.datT))
  # total profit
  cat(paste0('\tProfit of ',Scode,' was ',profit,'\n'))
  # plot 
  if (plot & length(Buydat) > 0) {
    SpyKplot(Scode,type = 'sting',bandTestres = bandRes,subtype = 'dailyK',plot = 'K-line',viewNum = viewNum) %>%
      addML(data = Buydat, symbolSize = c(1, 1), 
            effect = list(show = T,color = 'blue',loop = TRUE, period = 60, scaleSize = 1, shadowColor = NULL, shadowBlur=0))
  } else if (plot) {
    SpyKplot(Scode,type = 'sting',bandTestres = bandRes,subtype = 'dailyK',plot = 'K-line',viewNum = viewNum)}
}
```

### Stock trading footsteps of 000016

```{r, echo=TRUE}
bandTest = bandCrotest('000016', K_type = 'dailyK')
bandProfit('000016', bandRes = bandTest, plot = T)
StoQplot('000016', plot = c('StoIO'))
StoQplot('000016', plot = c('StoVP'))
```

### Stock trading footsteps of 300341

```{r, echo=TRUE}
bandTest = bandCrotest('300341', K_type = 'dailyK')
bandProfit('300341', bandRes = bandTest, plot = T)
StoQplot('300341', plot = c('StoIO'))
StoQplot('300341', plot = c('StoVP'))
```

### Stock trading footsteps of 002582

```{r, echo=TRUE}
bandTest = bandCrotest('002582', K_type = 'dailyK')
bandProfit('002582', bandRes = bandTest, plot = T)
StoQplot('002582', plot = c('StoIO'))
StoQplot('002582', plot = c('StoVP'))
```

Note: reports updated on 2020-05-20